### ISSUE TITLE
Doesn't work with python-docker 4.2.0

### ISSUE THREAD

**Issue by lemmy04** [Red5d/docker-autocompose#12]
```
lemmy@akari:~/Work/susebuildservice/home:lemmy04/python-docker-autocompose/t/docker-autocompose> python3 ./autocompose.py awx_task awx_web
Traceback (most recent call last):
  File "./autocompose.py", line 126, in <module>
    main()
  File "./autocompose.py", line 15, in main
    cfile, networks = generate(cname)
  File "./autocompose.py", line 30, in generate
    c = docker.from_env()
AttributeError: module 'docker' has no attribute 'from_env'
```

python-docker 2.0.0 is several years old by now, can this be adapted to python-docker 4.2.0?

**Comment by lemmy04** [comment]
it actually works fine... but installing the old python-docker-py with pip on top of the distro-provided python-docker 4.2.0 had seriously messed up things o.0
